### ISSUE TITLE
NG cockpit is used to manage customers & organizations entities

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_sergii#13]
As a **content manager**
I want to be able to change customers and organizations attributes in more modern way
So that backoffice extension is added to B2C accelerator

**AC:**
1. Organizations node is added to backoffice objects tree
2. Organizations manager is able to perform CRUD-operations with organizations & customers via backoffice web-page.

*Tips:*
https://wiki.hybris.com/display/release5/Include+-+Create+a+Custom+Backoffice+Extension 
https://wiki.hybris.com/display/tr52/Trail+~+Customizing+Backoffice+-+Cockpit+NG

**Comment by SergiiTy** [comment]
![13_crud_cust](https://cloud.githubusercontent.com/assets/17042159/15866184/3fcc4d6a-2ce6-11e6-99fd-5295a99d7656.JPG)

**Comment by SergiiTy** [comment]
![13_crud_org](https://cloud.githubusercontent.com/assets/17042159/15866201/59c475da-2ce6-11e6-98a4-655e3ed2ed6a.JPG)
