### ISSUE TITLE
Let organization customers receive e-mails

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_sergii#14]
As an **organization manager**
I want to be on the same page with organization contents
So that I receive daily email with list of users in my organization

**AC**
Email is sent to each organization manager whose address is set as an Organization.email attribute.
The email should contain list of all users in this organization. 

**Mail server configuration**
mail.from=darwinepam@gmail.com
mail.replyto=darwinepam@gmail.com
mail.smtp.server=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=darwinepam@gmail.com
mail.smtp.password=DarwinDarwin
mail.smtp.starttls.enable=true
mail.use.tls=true

**Comment by SergiiTy** [comment]
![14_org_email](https://cloud.githubusercontent.com/assets/17042159/15866176/34986f6e-2ce6-11e6-9885-02bc889229a5.JPG)
