### ISSUE TITLE
Run "organization e-mails" job using ant (without hybris started)

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_sergii#15]
As hybris **admin user**
I want to have a possibility to start "organization e-mails" cronjob without having hybris started
So that I have a bat script that starts this cronjob using ant.

**AC**
Needed .bat (or .sh) script is placed into a separate "admin" folder.

*Tips*
https://wiki.hybris.com/display/release5/cronjob+-+Technical+Guide#cronjob-TechnicalGuide-RunningCronJobsThroughAnt

**Comment by SergiiTy** [comment]
![15_ant_job](https://cloud.githubusercontent.com/assets/17042159/15888853/50649868-2d71-11e6-8d7d-35792eda9e71.JPG)
