### ISSUE TITLE
Obtain list of organizations via webservices

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_sergii#16]
As a **mobile developer or developer of integration candidate utility**
I want to have a possibility to obtain list of organizations via REST calls
So that webservices extension is configured properly

**AC**
Webservices extension is turned-on for B2C accelerator
Appropriate controllers are written
jUnit tests are written to test the functionality

*Tips:*
https://wiki.hybris.com/display/release5/Introduction+to+Web+Services
https://wiki.hybris.com/display/release5/Key+Features+and+Implementation+Details

**Comment by SergiiTy** [comment]
![16_ws](https://cloud.githubusercontent.com/assets/17042159/15888883/6c2808d2-2d71-11e6-923b-1dbf9085326a.JPG)
