### ISSUE TITLE
Generate an error message when organization name length is greater than 15 simbols

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_sergii#17]
As a **content manager**
I want to have a constraint for organization's name attribute
So that an appropriate constraint is created via ImpEx and is available in Admin cockpit.

**AC**
Aftert an attempt to set a long value for organization name an appropriate contraint generated an error
Constraint is created using ImpEx and could be changed in Admin cockpit

*Tips:*
https://wiki.hybris.com/display/R5T/Trail+~+Validation

**Comment by SergiiTy** [comment]
![17_constraint_1](https://cloud.githubusercontent.com/assets/17042159/15888891/77403b7c-2d71-11e6-8e4f-afbf3afde66a.JPG)

**Comment by SergiiTy** [comment]
![17_constraint_2](https://cloud.githubusercontent.com/assets/17042159/15888908/8840888c-2d71-11e6-815a-a29a70afeb20.JPG)
