### ISSUE TITLE
Interceptor is created to listen to organization fields change

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_sergii#18]
As **organization's customer**
I want to receive e-mail message when an amount of customers that belong to my organization becomes equal to 5
So that an appropriate intercepor is created to listen to such events.

**AC**
Each organization customer receives an e-mail message when its amount of customers becomes equal to 5

*Tips*
https://wiki.hybris.com/display/release5/Registering+Application+Event+Listener
https://wiki.hybris.com/display/release5/Event+System

**Comment by SergiiTy** [comment]
![18_interceptor](https://cloud.githubusercontent.com/assets/17042159/15889002/fef08acc-2d71-11e6-9247-656e23100a39.JPG)
