### ISSUE TITLE
Change default HAC URL to be “/hac”

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_sergii#19]
As **hybris admin** 
I want to have more flexible way to access hAC
So that to perform an access to hybris Admin Console I use "http://{host:port}/hac" URL

**AC**
Access to hAC is performer after sending a request to "http://{host:port}/hac" URL

*Tips*
local.properties file
hac.webroot && hmc.webroot properties there

**Comment by SergiiTy** [comment]
![19_hac](https://cloud.githubusercontent.com/assets/17042159/15888964/d3e65212-2d71-11e6-8e1c-64a721ffc325.JPG)
