### ISSUE TITLE
Mark an organization entity as 'catalogable' entity

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_sergii#20]
As a **content manager**
I want new Supplier model to be synchronizable among two OOTB catalogues (Staging and Online). 
So that I can synchronize my changes applied for Suppliers in catalogable manner.

**AC**
All Supplier attributes are synchronizable, accept id.

*Technical tips:*
https://wiki.hybris.com/display/release5/Synchronization+Guide
https://wiki.hybris.com/display/release5/Synchronization+of+Custom+Item +Types+-+5.2
https://wiki.hybris.com/display/release5/Classification+Guide
https://wiki.hybris.com/display/release5/Classification+Feature+Value+API
https://wiki.hybris.com/display/release5/Classification+System+API

*Hybris trail:*
https://wiki.hybris.com/display/R5T/Trail+~+Catalogs

**Comment by SergiiTy** [comment]
![20_cat_sync](https://cloud.githubusercontent.com/assets/17042159/15891527/a3594c92-2d7d-11e6-826c-5a79c8f526d1.JPG)
