### ISSUE TITLE
Create media folder to give a possibility to assign images to products from this folder

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_sergii#21]
As **hybris admin**
 I want to have a possibility to assign images to products selected from specially tuned media folder
 So that I have a folder where I can place images in and use them later from hMC.

**AC**
 Media folder is configured
 Images from media folder could be applied to products

_Technical tips_
https://wiki.hybris.com/display/release5/Secure+Media+Access
https://wiki.hybris.com/display/tr52/Trail+~+MediaConversion

**Comment by SergiiTy** [comment]
![21_media](https://cloud.githubusercontent.com/assets/17042159/15891539/b4ec07e2-2d7d-11e6-8e66-d64d354c140e.JPG)
