### ISSUE TITLE
Use facades layer to show some additional product data at PDP in a separate tab

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_sergii#22]
As a _customer_
 I want to have a possibility to look through additional information about product using a separate tab
 So that a new tab is available at **PDP**

**AC**:
* Features tab is created and displayed at PDP
* AdditionalInfo type is added to hybris to represent a simple String to display its contents at PDP
* Facades and populators are used
* ProductData is extended
* Relations are used to specify connections between list of additional info items and a product
* Additional option is available during the population of Product

_Technical tips_:
https://wiki.hybris.com/display/release5/How+to+Implement+Populators+and+Converters
https://wiki.hybris.com/pages/viewpage.action?pageId=252609501

_Results example_:
![4c273d3e-3865-11e5-9ab4-f4682ac3c581](https://cloud.githubusercontent.com/assets/12846266/14889067/dc74be0e-0d65-11e6-8ae6-2312bd7fc4e2.png)

**Comment by SergiiTy** [comment]
![22_feature](https://cloud.githubusercontent.com/assets/17042159/15891544/bf32e66c-2d7d-11e6-8abb-5319b3d0169d.JPG)
