### ISSUE TITLE
Develop an AddOn which allows to add random / theme images carousel via WCMS module

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/junior_hybris_mentoring_sergii#24]
As a *content manager*
I want to have a possibility to add random / theme images carousels to pages using CMS module means
So that an AddOn is developed which provides us this functionality

*Technical tips:*
https://wiki.hybris.com/display/R5T/Creating+New+CMS+Components

**Comment by SergiiTy** [comment]
![24_wcms_addon](https://cloud.githubusercontent.com/assets/17042159/15891565/d81bfa92-2d7d-11e6-892b-a60dec5bf9a3.JPG)
